-- Lisää DROP TABLE lauseet tähän tiedostoon

DROP TABLE IF EXISTS Marjastaja CASCADE;
DROP TABLE IF EXISTS Marja CASCADE;
DROP TABLE IF EXISTS Paikka CASCADE;
DROP TABLE IF EXISTS Kaynti CASCADE;
DROP TABLE IF EXISTS Suosikkimarja CASCADE;
DROP TABLE IF EXISTS Marjasaalis CASCADE;
